version: '3'

services:
  app:
    image: 'information-service:latest'
    restart: always
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/informationdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    volumes:
      - ./information-service:/information-service

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    volumes:
      - ./information-service/src/main/resources:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
volumes:
  postgres-data:
    driver: local